kind = "web"
previewPath = "/"
title = "ajTech"
version = "1.0.0"
id = "artifacts/ajtech"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 8082

[services.development]
run = "pnpm --filter @workspace/ajtech run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ajtech", "run", "build" ]
publicDir = "artifacts/ajtech/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "8082"
BASE_PATH = "/"
